de:
  languageName: Deutsch
  # Weight used for sorting.
  weight: 10
  taxonomies:
    tag: tags
    kategorie: kategorien

en:
  languageName: English
  contentDir: content/en
  weight: 20
  taxonomies:
    tag: tags
    category: categories
