de:
  languageName: Deutsch
  contentDir: content/de
  languageCode: de-DE
  # Weight used for sorting.
  weight: 10
  taxonomies:
    tag: tags
    kategorie: kategorien
en:
  languageName: English
  contentDir: content/en
  weight: 20
  disabled: false
  taxonomies:
    tag: tags
    category: categories
bs:
  languageName: Bosanski
  contentDir: content/bs
  weight: 30
  disabled: false
  taxonomies:
    nadimak: oznake
    kategorija: kategorije  
bg:
  languageName: Български
  contentDir: content/bg
  weight: 35
  disabled: false
  taxonomies:
    етикет: тагове
    категория: категории
cs:
  languageName: Čeština
  contentDir: content/cs
  weight: 40
  disabled: false
  taxonomies:
    značka: štítky
    kategorie: kategorie
da:
  languageName: Dansk
  contentDir: content/da
  disabled: false
  taxonomies:
    tag: tags
    kategori: kategorier
  weight: 45
et:
  languageName: Eesti
  contentDir: content/et
  weight: 50
  disabled: false
  taxonomies:
    silt: sildid
    kategooria: kategooriad
el:
  languageName: Ελληνικά
  contentDir: content/el
  weight: 55
  disabled: false
  taxonomies:
    ετικέτα: ετικέτες
    κατηγορία: κατηγορίες
es:
  languageName: Español
  contentDir: content/es
  title: Urban GmbH
  disabled: false
  taxonomies:
    etiqueta: etiquetas
    categoría: categorías
  weight: 60
fi:
  languageName: Suomalainen
  contentDir: content/fi
  weight: 125
  disabled: false
  taxonomies:
    tagi: tagit
    luokka: luokat  
fr:
  languageName: Français
  contentDir: content/fr
  disabled: false
  taxonomies:
    étiquette: étiquettes
    catégorie: catégories
  weight: 80
hr:
  languageName: Hrvatski
  contentDir: content/hr
  weight: 95
  disabled: false
  taxonomies:
    címke: címkék
    kategória: kategóriák
hu:
  languageName: Magyar
  contentDir: content/hu
  weight: 90
  disabled: false
  taxonomies:
    címke: címkék
    kategória: kategóriák  
it:
  languageName: Italiano
  contentDir: content/it
  disabled: false
  taxonomies:
    etichetta: etichette
    categoria: categorie
  weight: 93
lt:
  languageName: Lietuviškas
  contentDir: content/lt
  weight: 94
  disabled: false
  taxonomies:
    žyma: žymos
    kategorija: kategorijos  
lv:
  languageName: Latviešu
  contentDir: content/lv
  weight: 95
nl:
  languageName: Nederlands
  contentDir: content/nl
  disabled: false
  taxonomies:
    tag: tags
    categorie: categorieën
  weight: 100
no:
  languageName: Norsk
  contentDir: content/no
  weight: 110
  disabled: false
  taxonomies:
    merke: tagger
    kategori: kategorier
pl:
  languageName: Polski
  contentDir: content/pl
  weight: 120
  disabled: false
  taxonomies:
    znacznik: tagi
    kategoria: kategorie
pt:
  languageName: Português
  contentDir: content/pt
  disabled: false
  taxonomies:
    etiqueta: etiquetas
    categoria: categorias
  weight: 122
ro:
  languageName: Română
  contentDir: content/ro
  weight: 123
  disabled: false
  taxonomies:
    etichetă: etichete
    categorie: categorii  
ru:
  languageName: Русский
  contentDir: content/ru
  weight: 125
  disabled: false
  taxonomies:
    тег: теги
    категория: категории
sl:
  languageName: Slovenščina
  contentDir: content/sl
  weight: 125
  disabled: false
  taxonomies:
    oznaka: oznake
    kategorija: kategorije
sv:
  languageName: Svenska
  contentDir: content/sv
  weight: 128
  disabled: false
  taxonomies:
    tagg: taggar
    kategori: kategorier
tr:
  languageName: Türkçe
  contentDir: content/tr
  weight: 130
  disabled: false
  taxonomies:
    etiket: Etiketler
    Kategori: Kategoriler
uk:
  languageName: Український
  contentDir: content/uk
  weight: 150
  disabled: false
  taxonomies:
    тег: теги
    категорія: категорії
zh:
  languageName: 正體字/繁體字
  languageCode: zh-TW
  disabled: false
  contentDir: content/zh
  weight: 140
