de:
  label: Deutsch
  contentDir: content/de
  locale: de-DE
  # Weight used for sorting.
  weight: 10
  taxonomies:
    tag: tags
    kategorie: kategorien
en:
  label: English
  contentDir: content/en
  weight: 20
  disabled: false
  taxonomies:
    tag: tags
    category: categories
bs:
  label: Bosanski
  contentDir: content/bs
  weight: 30
  disabled: false
  taxonomies:
    nadimak: oznake
    kategorija: kategorije  
bg:
  label: Български
  contentDir: content/bg
  weight: 35
  disabled: false
  taxonomies:
    етикет: тагове
    категория: категории
cs:
  label: Čeština
  contentDir: content/cs
  weight: 40
  disabled: false
  taxonomies:
    značka: štítky
    kategorie: kategorie
da:
  label: Dansk
  contentDir: content/da
  disabled: false
  taxonomies:
    tag: tags
    kategori: kategorier
  weight: 45
et:
  label: Eesti
  contentDir: content/et
  weight: 50
  disabled: false
  taxonomies:
    silt: sildid
    kategooria: kategooriad
el:
  label: Ελληνικά
  contentDir: content/el
  weight: 55
  disabled: false
  taxonomies:
    ετικέτα: ετικέτες
    κατηγορία: κατηγορίες
es:
  label: Español
  contentDir: content/es
  disabled: false
  taxonomies:
    etiqueta: etiquetas
    categoría: categorías
  weight: 60
fi:
  label: Suomalainen
  contentDir: content/fi
  weight: 125
  disabled: false
  taxonomies:
    tagi: tagit
    luokka: luokat  
fr:
  label: Français
  contentDir: content/fr
  disabled: false
  taxonomies:
    étiquette: étiquettes
    catégorie: catégories
  weight: 80
hr:
  label: Hrvatski
  contentDir: content/hr
  weight: 95
  disabled: false
  taxonomies:
    címke: címkék
    kategória: kategóriák
hu:
  label: Magyar
  contentDir: content/hu
  weight: 90
  disabled: false
  taxonomies:
    címke: címkék
    kategória: kategóriák  
it:
  label: Italiano
  contentDir: content/it
  disabled: false
  taxonomies:
    etichetta: etichette
    categoria: categorie
  weight: 93
lt:
  label: Lietuviškas
  contentDir: content/lt
  weight: 94
  disabled: false
  taxonomies:
    žyma: žymos
    kategorija: kategorijos  
lv:
  label: Latviešu
  contentDir: content/lv
  weight: 95
nl:
  label: Nederlands
  contentDir: content/nl
  disabled: false
  taxonomies:
    tag: tags
    categorie: categorieën
  weight: 100
no:
  label: Norsk
  contentDir: content/no
  weight: 110
  disabled: false
  taxonomies:
    merke: tagger
    kategori: kategorier
pl:
  label: Polski
  contentDir: content/pl
  weight: 120
  disabled: false
  taxonomies:
    znacznik: tagi
    kategoria: kategorie
pt:
  label: Português
  contentDir: content/pt
  disabled: false
  taxonomies:
    etiqueta: etiquetas
    categoria: categorias
  weight: 122
ro:
  label: Română
  contentDir: content/ro
  weight: 123
  disabled: false
  taxonomies:
    etichetă: etichete
    categorie: categorii  
ru:
  label: Русский
  contentDir: content/ru
  weight: 125
  disabled: false
  taxonomies:
    тег: теги
    категория: категории
sl:
  label: Slovenščina
  contentDir: content/sl
  weight: 125
  disabled: false
  taxonomies:
    oznaka: oznake
    kategorija: kategorije
sv:
  label: Svenska
  contentDir: content/sv
  weight: 128
  disabled: false
  taxonomies:
    tagg: taggar
    kategori: kategorier
tr:
  label: Türkçe
  contentDir: content/tr
  weight: 130
  disabled: false
  taxonomies:
    etiket: Etiketler
    Kategori: Kategoriler
uk:
  label: Український
  contentDir: content/uk
  weight: 150
  disabled: false
  taxonomies:
    тег: теги
    категорія: категорії
zh:
  label: 正體字/繁體字
  locale: zh-TW
  disabled: false
  contentDir: content/zh
  weight: 140
