de:
  languageName: Deutsch
  contentDir: content/de
  languageCode: de-DE
  # Weight used for sorting.
  weight: 10
  taxonomies:
    tag: tags
    kategorie: kategorien
en:
  languageName: English
  contentDir: content/en
  weight: 20
  taxonomies:
    tag: tags
    category: categories
bs:
  languageName: Bosanski
  contentDir: content/bs
  weight: 30
bg:
  languageName: Български
  contentDir: content/bg
  weight: 35
cs:
  languageName: Čeština
  contentDir: content/cs
  weight: 40
da:
  languageName: Dansk
  contentDir: content/da
  weight: 45
et:
  languageName: Eesti
  contentDir: content/et
  weight: 50
el:
  languageName: Ελληνικά
  contentDir: content/el
  weight: 55
es:
  languageName: Español
  contentDir: content/es
  title: Urban GmbH
  taxonomies:
    etiqueta: etiquetas
    categoría: categorías
  weight: 60
fi:
  languageName: Suomalainen
  contentDir: content/fi
  weight: 125
fr:
  languageName: French
  contentDir: content/fr
  taxonomies:
    étiquette: étiquettes
    catégorie: catégories
  weight: 80
hr:
  languageName: Hrvatski
  contentDir: content/hr
  weight: 95
hu:
  languageName: Magyar
  contentDir: content/hu
  weight: 90
it:
  languageName: Italiano
  contentDir: content/it
  weight: 93
lt:
  languageName: Lietuviškas
  contentDir: content/lt
  weight: 94
lv:
  languageName: Latviešu
  contentDir: content/lv
  weight: 95
nl:
  languageName: Nederlands
  contentDir: content/nl
  taxonomies:
    tag: tags
    categorie: categorieën
  weight: 100
no:
  languageName: Norsk
  contentDir: content/no
  weight: 110
pl:
  languageName: Polski
  contentDir: content/pl
  weight: 120
pt:
  languageName: Português
  contentDir: content/pt
  weight: 122
ro:
  languageName: Română
  contentDir: content/ro
  weight: 123
ru:
  languageName: Русский
  contentDir: content/ru
  weight: 125
  taxonomies:
    тег: теги
    категория: категории
sl:
  languageName: Slovenščina
  contentDir: content/sl
  weight: 125
sv:
  languageName: Svenska
  contentDir: content/sv
  weight: 128
tr:
  languageName: Türkçe
  contentDir: content/tr
  weight: 130
uk:
  languageName: Український
  contentDir: content/uk
  weight: 150
zh:
  languageName: 正體字/繁體字
  languageCode: zh-TW
  contentDir: content/zh
  weight: 140
