main:
  - name: Structure du menu
    url: /docs/menu-tree/
    weight: 40
  - name: Application de démonstration
    url: /demo/
    weight: 42
  - name: Micrologiciel
    url: /docs/micrologiciel/
    weight: 42
