main:
  - name: Struktūros meniu
    url: /docs/menu-tree/
    weight: 30
  - name: Demonstracinė programa
    url: /demo/
    weight: 40
  - name: Programinė įranga
    url: /docs/firmware/
    weight: 50
