main:
  - name: Structura meniului
    url: /docs/menu-tree/
    weight: 30
  - name: Aplicație demo
    url: /demo/
    weight: 40
  - name: Oprogramowanie układowe
    url: /docs/firmware/
    weight: 50
