main:
  - name: Структура на менюто
    url: /docs/menu-tree/
    weight: 30
  - name: Демонстрационно приложение
    url: /demo/
    weight: 40
  - name: Фърмуер
    url: /docs/firmware/
    weight: 50
