title: Urban VitalControl
description: Gestione della salute 2.0
time_format_default: 02.01.2006
time_format_blog: 02.01.2006
copyright: Urban GmbH & Co.KG
privacy_policy: https://www.urbanonline.de/en/privacy-policy
taxonomy:
  # set taxonomyCloud: [] to hide taxonomy clouds
  taxonomyCloud:
    - categorie
    - etichette
  # If used, must have same length as taxonomyCloud
  taxonomyCloudTitle:
    - "Categorie"
    - "Tag cloud"
  # set taxonomyPageHeader: [] to hide taxonomies on the page headers
  taxonomyPageHeader:
    - categorie
    - etichette
