version: 2
updates:
  # Enable version updates for GitHub action workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "daily"
      time: "19:00"
    open-pull-requests-limit: 10
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
